app/models/home.py
from datetime import datetime
from app import db, ma


class string(db.Model):
    __tablename__ = "string"
    id = db.Column(db.Integer, primary_key=True)
    input = db.Column(db.String(255))
    last_modified = db.Column(db.DateTime, default=datetime.now)

    def __repr__(self):
        return '<Kelas a {}>'.format(self.input)


class stringSchema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model = string
        load_instance = True


class integer(db.Model):
    __tablename__ = "integer"
    id = db.Column(db.Integer, primary_key=True)
    input = db.Column(db.Integer)
    last_modified = db.Column(db.DateTime, default=datetime.now)

    def __repr__(self):
        return '<Kelas B {}>'.format(self.input)


class integerSchema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model = integer
        load_instance = True

app/models/user.py
from datetime import datetime
from app import db, ma
from werkzeug.security import generate_password_hash, check_password_hash


class User(db.Model):
    __tablename__ = "user"

    id_user = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.VARCHAR(50), nullable=False)
    email = db.Column(db.VARCHAR(50))
    password = db.Column(db.String(128), nullable=False)
    last_modified = db.Column(db.DateTime, default=datetime.now)

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def setPassword(self, password):
        self.password = generate_password_hash(password)
        return self.password

    def checkPassword(self, password):
        return check_password_hash(self.password, password)


class UserSchema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model = User
        load_instance = True

app/__init__.py
from app.controllers.register import register
from app.controllers.login import login
from app.controllers.home import home
from app.controllers import *
from flask import Flask, jsonify
from flask_sqlalchemy import SQLAlchemy
from flask_marshmallow import Marshmallow
from flask_migrate import Migrate
from flask_jwt_extended import *
from datetime import timedelta

app = Flask(__name__)
SQLALCHEMY_DATABASE_URI = 'mysql://root:''@db2/flask'

# SQLALCHEMY_DATABASE_URI = "mysql+mysqlconnector://{username}:{password}@{hostname}/{database}".format(
#     username="root",
#     password="123",
#     hostname="db2",
#     database="flask",)

app.config["SQLALCHEMY_DATABASE_URI"] = SQLALCHEMY_DATABASE_URI
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
SQLALCHEMY_TRACK_MODIFICATIONS = False
db = SQLAlchemy(app)
ma = Marshmallow(app)

app.config["SQLALCHEMY_DATABASE_URI"] = SQLALCHEMY_DATABASE_URI
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
# app.config['SECRET_KEY'] = 'super secret key'
SQLALCHEMY_TRACK_MODIFICATIONS = False
db = SQLAlchemy(app)
ma = Marshmallow(app)
migrate = Migrate(app, db)
app.config['JWT_SECRET_KEY'] = 'super-secret'
app.config['JWT_TOKEN_LOCATION'] = ['cookies']
app.config['JWT_ACCESS_TOKEN_EXPIRES'] = timedelta(minutes=30)
app.config['JWT_COOKIE_CSRF_PROTECT'] = True
app.config['JWT_CSRF_CHECK_FORM'] = True
jwt = JWTManager(app)


def assign_access_refresh_tokens(indetity):
    access_token = create_access_token(identity=str(indetity), fresh=True)
    refresh_token = create_refresh_token(identity=str(indetity))
    resp = jsonify({'login': True})
    set_access_cookies(resp, access_token)
    set_refresh_cookies(resp, refresh_token)
    return resp


# @jwt.additional_claims_loader
# def add_claims_to_access_token(indetity):
#     if indetity == "admin":
#         role = "Admin"
#     else:
#         role = "User"
#     return {
#         "role": role,
#         "name": indetity.upper(),
#     }


app.register_blueprint(home, url_prefix="/home")
app.register_blueprint(login, url_prefix="")
app.register_blueprint(register, url_prefix="/register")

app/controllers/__init__.py
from os.path import dirname, basename, isfile, join
import glob
modules = glob.glob(join(dirname(__file__), "*.py"))
__all__ = [basename(f)[:-3] for f in modules if isfile(f)
           and not f.endswith('__init__.py')]

app/controllers/home.py
from flask import render_template, request, jsonify, Blueprint, redirect, url_for, make_response
from flask.views import MethodView
from datetime import datetime
from app import db
from app.models.home import string, stringSchema, integer, integerSchema
from flask_jwt_extended import jwt_required, unset_jwt_cookies, get_jwt_identity

home = Blueprint('home', __name__)


@home.route('/')
@jwt_required()
def index():
    name = get_jwt_identity()
    return render_template('home.html', name=name)


@home.route('/logout')
def logout():
    resp = make_response(redirect(url_for('login.index')))
    unset_jwt_cookies(resp)
    return resp


class HomeController(MethodView):
    def post(self):
        json_data = request.get_json()
        input = json_data['input']
        select = json_data['select']
        if select == 'string':
            postDb = string(input=input)
        elif select == "integer":
            postDb = integer(input=input)
        db.session.add(postDb)
        db.session.commit()
        return jsonify(input)

    def get(self):
        dbString = string.query.all()
        schString = stringSchema(many=True)
        outString = schString.dump(dbString)
        dbInteger = integer.query.all()
        schInteger = integerSchema(many=True)
        outInteger = schInteger.dump(dbInteger)
        return jsonify({'Kelas A': outString}, {'Kelas B': outInteger})


home_view = HomeController.as_view('home_view')
home.add_url_rule('/post', view_func=home_view, methods=['POST'])
home.add_url_rule('/get', view_func=home_view, methods=['GET'])

app/controllers/login.py
from flask import render_template, request, Blueprint, jsonify
from flask.views import MethodView
from app.models.user import User
from app import assign_access_refresh_tokens

login = Blueprint('login', __name__)


@login.route('/')
def index():
    return render_template('login.html')


class loginController(MethodView):
    def post(self):
        json_data = request.get_json()
        user = json_data['user']
        password = json_data['password']

        user = User.query.filter_by(username=user).first()

        if not user or not user.checkPassword(password):
            resp = jsonify({'login': False})
            return resp
        return assign_access_refresh_tokens(user.username)


login_view = loginController.as_view('login_view')
login.add_url_rule('/post', view_func=login_view, methods=['POST'])

app/controllers/register.py
from flask import render_template, request, jsonify, Blueprint
from flask.views import MethodView
from app import db
from app.models.user import User

register = Blueprint('register', __name__)


@register.route('/')
def index():
    return render_template('register.html')


class registerController(MethodView):
    def post(self):
        json_data = request.get_json()
        user = json_data['user']
        email = json_data['email']
        password = json_data['password']

        hashPass = User().setPassword(password)
        postdb = User(username=user, email=email, password=hashPass)

        db.session.add(postdb)
        db.session.commit()

        return jsonify(user, email, hashPass)


register_view = registerController.as_view('register_view')
register.add_url_rule('/post', view_func=register_view, methods=['POST'])

app/templates/home.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <!-- Bootstrap CSS 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">-->
    <title>Hello</title>
  </head>
  <body>

      <h1>Selamat Datang
          {% if name %}{{name}}{% endif %}
          di Halaman Profile</h1>
    <br>
    <a href="{{ url_for('home.logout') }}"><button>Logout</button></a>
    <br><br>
    <div class="btn-group"> 
       
            <form action="" enctype="multipart/form-data" method="post">

    <div id="data">
        <input type="text" id="input">
        <label for="">Input Data</label>
                        <select id="select" class="dropdown">
                            <option value="string" name="string">String</option>
                            <option value="integer" name="integer">Integer</option>
                            <option value="boolean" name="boolean">Boolean</option>
                        </select>
        <button onclick="sendData()">send data</button>
        <button onclick="getData()">get data</button><br>
        <label for="">Input File</label>
        <input type="file" id="file" name="file" value="">
        <button onclick="upFile()">upload</button>
    </div>

    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>


    <script>
        function sendData() {
            var input = document.getElementById("input")
            var select = document.getElementById("select")
            axios
                .post('/home/post',{
                    input : input.value,
                    select : select.value
                })
                .then(res => showData(res))
                .catch(err => console.error(err));
        }


        function getData() {
            axios
                .get('/home/get', {
                  timeout: 5000
                })
                .then(function (response) {
                    _data = response.data;
                    document.getElementById('data').innerHTML =`<div><pre>${JSON.stringify(_data, null, 2)}</pre></div>`;
                })
        }

        function showData(res) {
          document.getElementById('res').innerHTML = `
            <div></div>
            <div><pre>${JSON.stringify(res.data, null, 2)}</pre></div>`;
        }

        function upFile() {
            var data = new FormData();
            data.append('file', document.getElementById('file').files[0]);
            axios
            .put('/put', data)
            .then(function (res) {
                console.log(res)
                })
        }
    </script>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />

    <title>Hello</title>
  </head>
  <body>
    <h1>Selamat Datang di Halaman Login</h1>
    <h4>Form Login</h4>

    <label for="user">Username</label>
    <input type="text" id="user" name="user" /><br />
    <label for="password">Password</label>
    <input type="password" id="password" name="password" /><br />
    <button onclick="PostRequest()">Login</button>

    <a href="{{url_for('register.index')}}"><button>Register</button></a>
    <div id="res"></div>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script>
      function PostRequest() {
        var user = document.getElementById("user");
        var password = document.getElementById("password");
        axios
          .post("/post", {
            user: user.value,
            password: password.value,
          })
          .then(function (res) {
            console.log(res.data.login);
            res = res.data.login;
            if (res == true) {
              window.location.href = "/home/";
            } else {
              document.getElementById("res").innerHTML =
                "Invalid Username/Password";
            }
          })
          .catch((err) => console.error(err));
      }
    </script>
  </body>
</html>

app/templates/register.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="./static/script.js"></script>
    <title>Hello</title>
  </head>
  <body>
    <h1>Selamat Datang di Halaman Register</h1>
    <h4>Form Register</h4>
    <form action="" method="post">
        <label for="user">Username :</label>
        <input type="text" id="user" name="user"><br>
        <label for="email">email :</label>
        <input type="text" id="email" name="email"><br>
        <label for="password">Password :</label>
        <input type="password" id="password" name="password"><br>
    </form>
    <a href="/"><button> Login</button></a></br>

    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script>
        function Submit() {
            var user = document.getElementById("user");
            var email = document.getElementById("email");
            var password = document.getElementById("password");
            
            axios
                .post('/register/post', {
                    user: user.value,
                    email: email.value,
                    password: password.value
                    
                })
                .then(window.location.reload())
                .catch(err => console.error(err));
        }

    </script>
</body>
</html>